# Generated by Django 3.0.3 on 2020-03-01 03:05

from django.db import migrations, models
import django_gvar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', django_gvar.models.GVarField(help_text='This is a test')),
            ],
        ),
    ]
