# Generated by Django 3.1a1 on 2020-06-19 13:34

from django.db import migrations, models
import django_gvar.serializers


class Migration(migrations.Migration):

    dependencies = [
        ('field_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedJSONFieldTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(decoder=django_gvar.serializers.GVarJSONDecoder, encoder=django_gvar.serializers.GVarJSONEncoder, help_text='Mixed GVar JSON field table.')),
            ],
        ),
    ]
